version: '3'

services:
  container0:
    build: ./httpserv/.
    command: ["7000"]
    volumes:
      - data-volume:/tmp/data-volume
      - ./sharedfolder:/tmp/sharedfolder
    ports:
     - "7000:7000"

  container1:
    build: ./httpserv/.
    command: ["8000"]
    volumes:
      - data-volume:/tmp/data-volume
      - ./sharedfolder:/tmp/sharedfolder
    ports:
     - "8000:8000"

  container2:
    build: ./httpserv/.
    command: ["9000"]
    volumes:
      - data-volume:/tmp/data-volume
      - ./sharedfolder:/tmp/sharedfolder
    ports:
     - "9000:9000"

  cloudslang:
    build: ./cloudslang/.
    command: ["run --f ../content/io/ping_hosts.sl --cp ../content/"]
    links:
     - container1
     - container2
     - container0

volumes:
  data-volume:
